MIN_PRICE = 0.000001
MIN_24H_VOLUME_USD = 1_000_000
MIN_HOURLY_VOLUME_USD = 25_000
MIN_BUY_SCORE = 25
MIN_SELL_SCORE = 55
MIN_TARGET_PROFIT_PCT = 3
TOP_RESULTS = 250

DEFAULT_VS_CURRENCY = "usd"
UNIVERSE_CACHE_SECONDS = 15 * 60
MARKET_DATA_INTERVAL = "1h"
MARKET_DATA_PERIOD = "7d"

STABLE_SYMBOLS = {
    "USDT",
    "USDC",
    "DAI",
    "BUSD",
    "FDUSD",
    "TUSD",
    "USDP",
    "PYUSD",
    "USDE",
    "EURC",
    "USDS",
    "USDD",
    "USD1",
    "USDX",
    "FRAX",
}
